/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FaceEnrollmentRouteImport } from './routes/face-enrollment'
import { Route as GroundTruthRouteImport } from './routes/ground-truth'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as MarkAttendanceRouteImport } from './routes/mark-attendance'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminCampusMapRouteImport } from './routes/admin.campus-map'
import { Route as AdminFaceEnrollmentRouteImport } from './routes/admin.face-enrollment'
import { Route as AdminFaceRequestsRouteImport } from './routes/admin.face-requests'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FaceEnrollmentRoute = FaceEnrollmentRouteImport.update({
  id: '/face-enrollment',
  path: '/face-enrollment',
  getParentRoute: () => rootRouteImport,
} as any)
const GroundTruthRoute = GroundTruthRouteImport.update({
  id: '/ground-truth',
  path: '/ground-truth',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkAttendanceRoute = MarkAttendanceRouteImport.update({
  id: '/mark-attendance',
  path: '/mark-attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/admin/attendance',
  path: '/admin/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCampusMapRoute = AdminCampusMapRouteImport.update({
  id: '/admin/campus-map',
  path: '/admin/campus-map',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFaceEnrollmentRoute = AdminFaceEnrollmentRouteImport.update({
  id: '/admin/face-enrollment',
  path: '/admin/face-enrollment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFaceRequestsRoute = AdminFaceRequestsRouteImport.update({
  id: '/admin/face-requests',
  path: '/admin/face-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/admin/staff',
  path: '/admin/staff',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/face-enrollment': typeof FaceEnrollmentRoute
  '/ground-truth': typeof GroundTruthRoute
  '/history': typeof HistoryRoute
  '/mark-attendance': typeof MarkAttendanceRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/campus-map': typeof AdminCampusMapRoute
  '/admin/face-enrollment': typeof AdminFaceEnrollmentRoute
  '/admin/face-requests': typeof AdminFaceRequestsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/face-enrollment': typeof FaceEnrollmentRoute
  '/ground-truth': typeof GroundTruthRoute
  '/history': typeof HistoryRoute
  '/mark-attendance': typeof MarkAttendanceRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/campus-map': typeof AdminCampusMapRoute
  '/admin/face-enrollment': typeof AdminFaceEnrollmentRoute
  '/admin/face-requests': typeof AdminFaceRequestsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/face-enrollment': typeof FaceEnrollmentRoute
  '/ground-truth': typeof GroundTruthRoute
  '/history': typeof HistoryRoute
  '/mark-attendance': typeof MarkAttendanceRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/campus-map': typeof AdminCampusMapRoute
  '/admin/face-enrollment': typeof AdminFaceEnrollmentRoute
  '/admin/face-requests': typeof AdminFaceRequestsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/face-enrollment'
    | '/ground-truth'
    | '/history'
    | '/mark-attendance'
    | '/profile'
    | '/settings'
    | '/admin/attendance'
    | '/admin/audit-logs'
    | '/admin/campus-map'
    | '/admin/face-enrollment'
    | '/admin/face-requests'
    | '/admin/staff'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/face-enrollment'
    | '/ground-truth'
    | '/history'
    | '/mark-attendance'
    | '/profile'
    | '/settings'
    | '/admin/attendance'
    | '/admin/audit-logs'
    | '/admin/campus-map'
    | '/admin/face-enrollment'
    | '/admin/face-requests'
    | '/admin/staff'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/face-enrollment'
    | '/ground-truth'
    | '/history'
    | '/mark-attendance'
    | '/profile'
    | '/settings'
    | '/admin/attendance'
    | '/admin/audit-logs'
    | '/admin/campus-map'
    | '/admin/face-enrollment'
    | '/admin/face-requests'
    | '/admin/staff'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FaceEnrollmentRoute: typeof FaceEnrollmentRoute
  GroundTruthRoute: typeof GroundTruthRoute
  HistoryRoute: typeof HistoryRoute
  MarkAttendanceRoute: typeof MarkAttendanceRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminCampusMapRoute: typeof AdminCampusMapRoute
  AdminFaceEnrollmentRoute: typeof AdminFaceEnrollmentRoute
  AdminFaceRequestsRoute: typeof AdminFaceRequestsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/face-enrollment': {
      id: '/face-enrollment'
      path: '/face-enrollment'
      fullPath: '/face-enrollment'
      preLoaderRoute: typeof FaceEnrollmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ground-truth': {
      id: '/ground-truth'
      path: '/ground-truth'
      fullPath: '/ground-truth'
      preLoaderRoute: typeof GroundTruthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mark-attendance': {
      id: '/mark-attendance'
      path: '/mark-attendance'
      fullPath: '/mark-attendance'
      preLoaderRoute: typeof MarkAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/admin/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/campus-map': {
      id: '/admin/campus-map'
      path: '/admin/campus-map'
      fullPath: '/admin/campus-map'
      preLoaderRoute: typeof AdminCampusMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/face-enrollment': {
      id: '/admin/face-enrollment'
      path: '/admin/face-enrollment'
      fullPath: '/admin/face-enrollment'
      preLoaderRoute: typeof AdminFaceEnrollmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/face-requests': {
      id: '/admin/face-requests'
      path: '/admin/face-requests'
      fullPath: '/admin/face-requests'
      preLoaderRoute: typeof AdminFaceRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/admin/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FaceEnrollmentRoute: FaceEnrollmentRoute,
  GroundTruthRoute: GroundTruthRoute,
  HistoryRoute: HistoryRoute,
  MarkAttendanceRoute: MarkAttendanceRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminCampusMapRoute: AdminCampusMapRoute,
  AdminFaceEnrollmentRoute: AdminFaceEnrollmentRoute,
  AdminFaceRequestsRoute: AdminFaceRequestsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
